spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/dsiApp
spring.datasource.username=aliazgorrumi
spring.datasource.password=

server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.dsi.ruet.backend=DEBUG

# Mail config (Gmail SMTP — replace with your credentials)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rmdashikur72@gmail.com
spring.mail.password=ibrj arqb qlvi tptz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.from=rmdashikur72@gmail.com

spring.profiles.active=dev
